### ISSUE TITLE
pandas not found after conda installation

### ISSUE THREAD

**Issue by tillysscott** [qjiangzhao/TEtrimmer#34]
Hello, I have installed TEtrimmer into a conda environment using mamba, as detailed in the readme.md . I am on Linux  

```
TEtrimmer --help
```
pulls up the help menu successfully. When I try to run TEtrimmer on the test data 7 out of 8 sequences aren't analysed. The standard out prints:
```
MSA plot failed rnd_1_family_667 with error:
infer_objects() got an unexpected keyword argument 'copy'
```
Within the Multiple_sequence_alignment/error_file.txt
```
Error when doing ORF and PFAM prediction for input sequence rnd_1_family_667
Traceback (most recent call last):
  File "/uoa/scratch/users/r01ms21/apps/TEtrimmer/tetrimmer/analyze.py", line 664, in analyze_sequence
    if input_orf_pfam_obj.run_getorf():
  File "/uoa/scratch/users/r01ms21/apps/TEtrimmer/tetrimmer/orfdomain.py", line 192, in run_getorf
    subprocess.run(get_orf_command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/software/uoa/spack-sw/linux-rhel8-x86_64/gcc-12.1.0/python-3.9.12-u2o5ndnqcbr26nc573ubjrvv7o5n5wts/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/software/uoa/spack-sw/linux-rhel8-x86_64/gcc-12.1.0/python-3.9.12-u2o5ndnqcbr26nc573ubjrvv7o5n5wts/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/software/uoa/spack-sw/linux-rhel8-x86_64/gcc-12.1.0/python-3.9.12-u2o5ndnqcbr26nc573ubjrvv7o5n5wts/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 14] Bad address: 'getorf'

MSA plot failed for rnd_1_family_667 with error:
infer_objects() got an unexpected keyword argument 'copy'
Traceback (most recent call last):
  File "/uoa/scratch/users/r01ms21/apps/TEtrimmer/tetrimmer/boundarycrop.py", line 742, in find_boundary_and_crop
    MSA_plot = process_msa(cropped_boundary_plot_concatenate, output_dir, concat_start, concat_end, sequence_len)
  File "/uoa/scratch/users/r01ms21/apps/TEtrimmer/tetrimmer/MSAcluster.py", line 645, in process_msa
    alignment_color_df = replace_bases(alignment_df, base_mapping)
  File "/uoa/scratch/users/r01ms21/apps/TEtrimmer/tetrimmer/MSAcluster.py", line 540, in replace_bases
    result_obj = result_obj.infer_objects(copy=False)
TypeError: infer_objects() got an unexpected keyword argument 'copy'
```
pandas is definitely installed into the conda environment and the environment is activated. Any suggestions?

**Comment by qjiangzhao** [comment]
Hi,

For the first error:
TEtrimmer used the follwing command for ORF prediction:
`getorf -sequence <input.fasta> -outseq <orf_output_file> -minsize 100`
You can try to run this in your terminal to test "getorf". If "getorf" isn't available, install it by `mamba install bioconda::emboss` or update it by `mamba update -c bioconda emboss`

For the second error:
You can try to update your panda by `conda update -c conda-forge pandas` 

If the errors still exist. You can add `--debug` option when you run TEtrimmer and send me all the standard output. I will have another look. 

Yours sincerely
Jiangzhao

**Comment by tillysscott** [comment]
Hello! My IT department installed it for me and now it works. Thank you for the programme and helping
