### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/xxx/xxx.TEtrimmer/Classification_and_deduplication/TEtrimmer_consensus_no_low_copy.fasta'

### ISSUE THREAD

**Issue by xiaoguizz** [qjiangzhao/TEtrimmer#48]
Hello,
      When I ran TEtrimmer, I cleaned the data with repeatmasker's results to get more accurate TE annotation results, but out of the 5000 repeatmasker's TE annotations that I chose, I found that there were only three TEs that TEtrimmer finally recognized as correct, and I'm not sure that I got the right one, and I also got some errors during my run. I'm not sure if what I got is correct, and I also got some errors during my run, and I found that my result analysis is only 80% complete, and I'm not sure if my result is credible or not.In addition, I'm curious if I'd be better off using DETA as input or repeatmasker's results.As I mentioned above some of the errors reported are as follows:
Final clustering of proof curation files failed with error [Errno 2] No such file or directory: '/xxx/xx.TEtrimmer/Classification_and_deduplication/TEtrimmer_consensus_no_low_copy.fasta'

Traceback (most recent call last):
  File "/xxx/tetrimmer/TEtrimmer.py", line 531, in main
    analyze.cluster_proof_anno_file(
  File "/xxx/tetrimmer/analyze.py", line 492, in cluster_proof_anno_file
    final_con_file_no_low_copy_dict = fasta_file_to_dict(final_con_file_no_low_copy, separate_name=True)
  File "/xxx/tetrimmer/functions.py", line 129, in fasta_file_to_dict
    for record in SeqIO.parse(input_file, "fasta"):
  File "/xxx/envs/TEtrimmer/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 625, in parse
    return iterator_generator(handle)
  File "/xxx/envs/TEtrimmer/lib/python3.10/site-packages/Bio/SeqIO/FastaIO.py", line 187, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/xxx/envs/TEtrimmer/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 64, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/xxx/xxx.TEtrimmer/Classification_and_deduplication/TEtrimmer_consensus_no_low_copy.fasta'

This does not affect the final TE consensus sequences. But this can heavily complicate the TE proof curation. If you don't plan to do proof curation, you can choose to ignore this error.

TEtrimmer is performing whole-genome TE annotation by RepeatMasker. This could take long time.
The final TE consensus library has been completed. You can use it now.

Finished whole genome TE annotation by RepeatMasker

Progress: |████████████████████████████████████████----------| 4080/5000 = 81.6% Complete
Very much looking forward to your reply!

**Comment by qjiangzhao** [comment]
Hi @xiaoguizz,

Thanks for your question and sorry for the late reply due to my holiday. Have you tried the test file of TEtrimmer? If you haven't, please do that first and makesure the configuration of TEtrimmer is correct. 

Yours sincerely
Jiangzhao Qian
